---

- name: Install git
  win_chocolatey:
    name: git
    state: present

- name: Check if existing Palantir osquery-configuration directory
  win_stat:
    path: 'c:\Program Files\osquery\palantir-configuration'
  register: dir

- name: Git clone palantir/osquery-configuration
  win_shell: git clone https://github.com/palantir/osquery-configuration.git palantir-configuration
  args:
    chdir: 'c:\Program Files\osquery'
  when: not dir.stat.exists

- name: Instal palantir packs
  win_copy:
    src: "c:\\Program Files\\osquery\\palantir-configuration\\Classic\\Endpoints\\packs\\{{ item }}.conf"
    dest: "c:\\Program Files\\osquery\\packs\\{{ item }}.conf"
    remote_src: true
  with_items: "{{ win_osquery_packs_palantir }}"

- name: Set packs with palantir's
  set_fact:
    win_osquery_packs: "{{ win_osquery_packs + win_osquery_packs_palantir }}"
