---

- meta: flush_handlers

- name: pause a bit to have few queries results
  pause:
#    minutes: 5
    seconds: 60

- name: Edit few registry keys
  win_regedit:
    key: "{{ item.k }}"
    value: "{{ item.v }}"
    data: "{{ item.d }}"
    datatype: "{{ item.t }}"
  with_items:
    - { k: "HKLM:\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System", v: "EnableLUA", d: 0, t: dword }
    - { k: "HKCU:\\Software\\Microsoft\\Office\\16.0\\Outlook\\Security", v: "ShowOLEPackageObj", d: 1, t: dword }
    - { k: "HKCU:\\Software\\Policies\\Google\\Chrome", v: "DownloadRestrictions", d: 0, t: dword }

- name: pause again
  pause:
    seconds: 60

- block:
    - name: Check osquery log - file
      win_shell: Get-Content -Path "{{ win_osquery_dir }}\log\osqueryd.results.log"
      register: results
      ignore_errors: true
      changed_when: false
    - debug: var=results.stdout_lines
  when:
    - "'windows_event_log' not in win_osquery_logger_plugin"

- block:
    - name: upload Get-OsqueryXMLEvtLogs.ps1
      win_template:
        src: Get-OsqueryXMLEvtLogs.ps1
        dest: "{{ win_osquery_dir }}\\Get-OsqueryXMLEvtLogs.ps1"
    - name: Check osquery logs - Event log
      #win_shell: Get-WinEvent -LogName 'osquery'
      win_shell: "\"{{ win_osquery_dir }}\\Get-OsqueryXMLEvtLogs.ps1\""
      register: winevt
      ignore_errors: true
      changed_when: false
    - debug: var=winevt.stdout_lines
  when:
    - "'windows_event_log' in win_osquery_logger_plugin"
