---

- name: Restart osqueryd
  win_service:
    name: osquery daemon service
    state: restarted
  when: win_osquery_url is not defined or not win_osquery_url

- name: Restart osqueryd - script
  win_shell: "{{ item }}"
  with_items:
    - "PowerShell.exe -ExecutionPolicy Bypass -File \"{{ win_osquery_dir }}\\manage-osqueryd.ps1\" -stop"
    - "PowerShell.exe -ExecutionPolicy Bypass -File \"{{ win_osquery_dir }}\\manage-osqueryd.ps1\" -start"
  when: win_osquery_url is defined and win_osquery_url
